name: Go Build, Test, and Docker Build/Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=30m -v
        
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run golang test
        run: go test -v ./...

  build-docker-image-gateway-mt:
    environment: development
    needs: ["lint", "test"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/dev/gateway-mt:${{ github.sha }}, ghcr.io/${{ github.repository_owner }}/${{ github.repository }}/dev/gateway-mt:latest
          push: false
          context: .
          file: cmd/gateway-mt/Dockerfile
          build-args: |
            DOCKER_ARCH=${{ vars.DOCKER_ARCH }}
            GO_VERSION=${{ vars.GO_VERSION }}
            IMAGE_VERSION=${{ vars.IMAGE_VERSION }}
            DOCKER_OS=${{ vars.DOCKER_OS }}

  build-docker-image-authservice:
    environment: development
    needs: ["lint", "test"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/${{ github.repository }}/dev/authservice:${{ github.sha }}
            ghcr.io/${{ github.repository }}/dev/authservice:latest
          push: false
          context: .
          file: cmd/authservice/Dockerfile
          build-args: |
            DOCKER_ARCH=${{ vars.DOCKER_ARCH }}
            GO_VERSION=${{ vars.GO_VERSION }}
            IMAGE_VERSION=${{ vars.IMAGE_VERSION }}
            DOCKER_OS=${{ vars.DOCKER_OS }}

