name: Postmerge

on:
  pull_request:
    types: ["closed"]
    branches:
      - main

jobs: 
  create-tag:
    if: github.event.pull_request.merged == true
    name: Bump version and push tags
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Create tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: ${{ vars.INITIAL_VERSION }}

      - name: "set output version"
        id: set_version
        run: echo "version=${{ steps.create_tag.outputs.new_tag }}" >> $GITHUB_OUTPUT

  build-dev-images:
    if: github.event.pull_request.merged == true
    needs: [create-tag]
    name: Build dev images
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: test
        run: |
          echo $PWD
          ls -a

      - name: Build authservice dev docker image
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/${{ github.repository }}/dev/authservice:${{ github.sha }}
            ghcr.io/${{ github.repository }}/dev/authservice:${{ needs.create-tag.outputs.version }}
            ghcr.io/${{ github.repository }}/dev/authservice:latest
          push: true
          context: .
          file: cmd/authservice/Dockerfile
          build-args: |
            DOCKER_ARCH=${{ vars.DOCKER_ARCH }}
            GO_VERSION=${{ vars.GO_VERSION }}
            IMAGE_VERSION=${{ vars.IMAGE_VERSION }}
            DOCKER_OS=${{ vars.DOCKER_OS }}

      - name: Build gateway-mt dev docker image
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/${{ github.repository }}/dev/gateway-mt:${{ github.sha }}
            ghcr.io/${{ github.repository }}/dev/gateway-mt:${{ needs.create-tag.outputs.version }}
            ghcr.io/${{ github.repository }}/dev/gateway-mt:latest
          push: true
          context: .
          file: cmd/gateway-mt/Dockerfile
          build-args: |
            DOCKER_ARCH=${{ vars.DOCKER_ARCH }}
            GO_VERSION=${{ vars.GO_VERSION }}
            IMAGE_VERSION=${{ vars.IMAGE_VERSION }}
            DOCKER_OS=${{ vars.DOCKER_OS }}