name: Postmerge

on:
  pull_request:
    types: ["closed"]
    branches:
      - main

jobs: 
  create-tag:
    if: github.event.pull_request.merged == true
    name: Bump version and push tags
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Create tag
        id: create_tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
          WITH_V: true
          DEFAULT_BUMP: patch
          INITIAL_VERSION: ${{ vars.INITIAL_VERSION }}

      - name: "set output version"
        id: set_version
        run: echo "version=${{ steps.create_tag.outputs.new_tag }}" >> $GITHUB_OUTPUT