name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
  arch: aarch64
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
  - name: Build the hello-docker Docker image
run: |
  docker build cmd/gateway-mt --tag ghcr.io/deweb-services/gateway-mt/feat/add-bucket-substitution/gateway-mt:111
  docker run ghcr.io/deweb-services/gateway-mt/feat/add-bucket-substitution/gateway-mt:111
  docker push ghcr.io/deweb-services/gateway-mt/feat/add-bucket-substitution/gateway-mt:111