name: publish
on: push
jobs:
  publish-gateway-mt-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/gateway-mt/Dockerfile
          platforms: linux/amd64
          push: true
          tags:
            repo:test-latest
