name: Release gateway-mt

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: gateway-mt desired release version
        required: true
      commit:
        type: string
        description: Commit hash reference to make a release from
        required: true

jobs:

  build-gateway-stage:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.commit }}

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ inputs.version }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/${{ github.repository }}/staging/gateway-mt:${{ github.sha }}
            ghcr.io/${{ github.repository }}/staging/gateway-mt:${{ inputs.version }}
          push: true
          context: .
          file: cmd/gateway-mt/Dockerfile
          build-args: |
            DOCKER_ARCH=${{ vars.DOCKER_ARCH }}
            GO_VERSION=${{ vars.GO_VERSION }}
            IMAGE_VERSION=${{ vars.IMAGE_VERSION }}
            DOCKER_OS=${{ vars.DOCKER_OS }}
  
  build-gateway-prod:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ inputs.commit }}

      - name: Create tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ inputs.version }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/${{ github.repository }}/production/gateway-mt:${{ github.sha }}
            ghcr.io/${{ github.repository }}/production/gateway-mt:${{ inputs.version }}
          push: true
          context: .
          file: cmd/gateway-mt/Dockerfile
          build-args: |
            DOCKER_ARCH=${{ vars.DOCKER_ARCH }}
            GO_VERSION=${{ vars.GO_VERSION }}
            IMAGE_VERSION=${{ vars.IMAGE_VERSION }}
            DOCKER_OS=${{ vars.DOCKER_OS }}