name: Release gateway-mt

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build-gateway-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          tags: |
            ghcr.io/${{ github.repository }}/gateway-mt:latest
            ghcr.io/${{ github.repository }}/gateway-mt:${{ github.sha }}
            ghcr.io/${{ github.repository }}/gateway-mt:${{ github.ref_name }}
          push: true
          context: .
          file: cmd/gateway-mt/Dockerfile
          build-args: |
            DOCKER_ARCH=${{ vars.DOCKER_ARCH }}
            GO_VERSION=${{ vars.GO_VERSION }}
            IMAGE_VERSION=${{ vars.IMAGE_VERSION }}
            DOCKER_OS=${{ vars.DOCKER_OS }}